### ISSUE TITLE
Align numbers by dot

### ISSUE THREAD

**Issue by xtay573269555** [wfxr/csview#182]
## Check list

- [x] I have read through the [README](https://github.com/wfxr/csview/blob/master/README.md)
- [x] I have searched through the existing issues

## Environment info

- OS
    - [x] Linux
    - [ ] Mac OS X
    - [ ] Windows
    - [ ] Others:

## Version
csview 1.2.2

## Problem / Steps to reproduce

The output of `my_number` column is the following:
```
┌────┬────────┬─────────────┬──────────┐
│ Id │  Sex   │ my_number   │ Embarked │
├────┼────────┼─────────────┼──────────┤
│ 1  │ male   │ 12345.54321 │ S        │
│ 2  │ female │ 123.321     │ C        │
│ 3  │ female │ 123         │ S        │
│ 4  │ female │ 12.21       │ S        │
│ 5  │ male   │ 1.1         │ S        │
│ 6  │ male   │ 0.1         │ S        │
│ 7  │ male   │ 0.01        │ S        │
│ 8  │ male   │ 0.001       │ S        │
└────┴────────┴─────────────┴──────────┘
```

The output of `my_number` column in my mind is the following:
```
┌────┬────────┬─────────────┬──────────┐
│ Id │  Sex   │ my_number   │ Embarked │
├────┼────────┼─────────────┼──────────┤
│ 1  │ male   │ 12345.54321 │ S        │
│ 2  │ female │   123.321   │ C        │
│ 3  │ female │   123       │ S        │
│ 4  │ female │    12.21    │ S        │
│ 5  │ male   │     1.1     │ S        │
│ 6  │ male   │     0.1     │ S        │
│ 7  │ male   │     0.01    │ S        │
│ 8  │ male   │     0.001   │ S        │
└────┴────────┴─────────────┴──────────┘
```

**Comment by wfxr** [comment]
Hi @xtay573269555, I see your suggestion. But this would be a heavy feature that requires `csview` to have a way to identify the actual data type of each column, and cache all the input fields to compute the right padding. Both of them will make `csview` not fast and memory efficient as it aimed to be.
