### ISSUE TITLE
About 1.2.3 release

### ISSUE THREAD

**Issue by chenrui333** [wfxr/csview#190]
👋 it looks like 1.2.3 release did not get completed (ie did not get marked as latest release), raise this issue for some awareness. Thanks!

cc @wfxr 

relates to https://github.com/Homebrew/homebrew-core/pull/163690

**Comment by chenrui333** [comment]
cc @wfxr

**Comment by chenrui333** [comment]
cool cool! 👍

**Comment by wfxr** [comment]
@chenrui333 the ci should be fixed by #191

**Comment by chenrui333** [comment]
Thanks @wfxr, gonna try it out in https://github.com/Homebrew/homebrew-core/pull/164990
