### ISSUE TITLE
Generate a Universal Binary for Mac

### ISSUE THREAD

**Issue by ondohotola** [wfxr/csview#204]
## Check list

- [x] I have read through the [README](https://github.com/wfxr/csview/blob/master/README.md)
- [x] I have searched through the existing issues

## Environment info

- OS
    - [ ] Linux
    - [X] Mac OS X
    - [ ] Windows
    - [ ] Others:

## Version

1.3.1

## Problem / Steps to reproduce

When I look at the Assets I see there is only one for the Mac INTEL processor, and not a Universal one or one for the ARM one.
Homebrew will send me one for ARM (when they come to it :-)-O) and the Intel one works on the Arm with Rosetta, but maybe one can adapt the rule to generate a Universal binary, or if that is not possible to generate one for Intel and one for Arm.

**Comment by wfxr** [comment]
Added arm64 binary for macos. You can find it from the release page (named `csview-v1.3.2-aarch64-apple-darwin.tar.gz`).

**Comment by ondohotola** [comment]
Great, thanks. Homebrew has upgraded its ARM version too

**Comment by ondohotola** [comment]
And Homebrew now has 1.3.2
