### ISSUE TITLE
question: Does csview fixed the stream rendering?

### ISSUE THREAD

**Issue by zhiburt** [wfxr/csview#61]
Hi @wfxr 

I bump into csview by

https://github.com/phsym/prettytable-rs/issues/104
https://github.com/wfxr/csview/issues/19

I think it's a great idea to not allocate the huge chunk of memory but rather do things lazily.

And I was thinking how to do it myself https://github.com/zhiburt/tabled/issues/123
I was thinking about requiring `Clone` for iterator so 1 pass for demension the second pass when print.
But it seems to be restrictive to me.

So I looked at your ideas.

And I just wonder if you've fixed the original issue.

Specifically my concern is about this `Vec` allocation.

https://github.com/wfxr/csview/blob/5a1e6d9e353313a1ebd86cd01e712458e4c94321/src/table/mod.rs#L20
https://github.com/wfxr/csview/blob/5a1e6d9e353313a1ebd86cd01e712458e4c94321/src/table/mod.rs#L79

Am I wrong that essentially we will allocate `n * m` memory anyway here.

Take care.
Thank you for cross issue references :) 

## Check list

- [x] I have read through the [README](https://github.com/wfxr/csview/blob/master/README.md)
- [x] I have searched through the existing issues

## Environment info

- OS
    - [x] Linux
    - [x] Mac OS X
    - [x] Windows
    - [x] Others:

**Comment by wfxr** [comment]
Hi @zhiburt , `sniff_rows` is for detecting reasonable widths for each column. It is provided by the cli options `--sniff` (default 1000). And you are right, we still need to pre-allocate some memory to store the rows during sniffing because we cannot read them twice.  But the memory usage will no longer grow once sniff finished. It's not a big deal since we only need to store constant number of rows.

The benchmarks section shows the memory usage in some common scenario:
https://github.com/wfxr/csview#benchmark

**Comment by wfxr** [comment]
> Am I wrong that essentially we will allocate n * m memory anyway here.
> https://github.com/wfxr/csview/blob/5a1e6d9e353313a1ebd86cd01e712458e4c94321/src/table/mod.rs#L20
> https://github.com/wfxr/csview/blob/5a1e6d9e353313a1ebd86cd01e712458e4c94321/src/table/mod.rs#L79

`buf` here is to store the sniffed rows, not all rows from input.

**Comment by zhiburt** [comment]
> Hi @zhiburt , sniff_rows is for detecting reasonable widths for each column. It is provided by the cli options --sniff (default 1000). And you are right, we still need to pre-allocate some memory to store the rows during sniffing because we cannot read them twice. But the memory usage will no longer grow once sniff finished. It's not a big deal since we only need to store constant number of rows.

I see

So when the `--sniff` argument is not provided we essentially will allocate memory for all rows right?

PS: Correct me if I am wrong but in case `--sniff` was 1000 but 1001 row "very big" compared to the ones in first 1000 chunk the displayed table will be broken?

**Comment by zhiburt** [comment]
As I understand it is assumed that `--sniff` always be set to some value right?

https://github.com/wfxr/csview/blob/5a1e6d9e353313a1ebd86cd01e712458e4c94321/src/table/mod.rs#L26

**Comment by wfxr** [comment]
> As I understand it is assumed that `--sniff` always be set to some value right?
@zhiburt Right. If sniff not set by user it will take the default value 1000. You can also assign it to `0` which will disable `sniff` mechanism and in this case `csview` will load all rows in memory to calculate the exact width of each column before printing.
