### ISSUE TITLE
Support distribution on Linux via Linuxbrew

### ISSUE THREAD

**Issue by vamega** [wfxr/csview#7]
## Check list

- [x] I have read through the [README](https://github.com/wfxr/csview/blob/master/README.md)
- [x] I have searched through the existing issues

## Environment info

- OS
    - [x] Linux
    - [ ] Mac OS X
    - [ ] Windows
    - [ ] Others:

## Version

N/A

## Problem / Steps to reproduce

Running `brew tap wxfr/csview && brew install csview` on Linux with Linuxbrew, does not result in a working `csview`.
I looked at the `homebrew-csview` repository, and the darwin binary is hard coded there.

I'm not sure if it's possible, but is there a way that you could support distributing on Linux via Linuxbrew?

**Comment by wfxr** [comment]
Hi @vamega Can linuxbrew and homebrew share the same formula? I'm happy to add support for linuxbrew but I'm not familiar with it. PRs or any help are welcomed!

**Comment by vamega** [comment]
I'm going to investigate that.
I'm only minimally familiar with homebrew packaging myself.

Thanks for the great tool
