### ISSUE TITLE
Center Headers?

### ISSUE THREAD

**Issue by ondohotola** [wfxr/csview#78]
## Check list

- [ X] I have read through the [README](https://github.com/wfxr/csview/blob/master/README.md)
- [ X] I have searched through the existing issues

## Environment info

- OS
    - [ X] Linux
    - [X ] Mac OS X
    - [X ] Windows
    - [ ] Others:

## Version

csview 1.1.0

## Problem / Steps to reproduce

Would it be possible to center the headers of the columns (if any)?

**Comment by wfxr** [comment]
Hi @ondohotola , thanks for yor suggestion. This feature has been implemented in https://github.com/wfxr/csview/pull/90. Welcome to try!
